# Generated by Django 3.0.7 on 2021-03-05 14:55

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20191127_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=markdownx.models.MarkdownxField(help_text='Please write Markdown format. header content start for h3.', verbose_name='Content'),
        ),
    ]
